# Generated by Django 3.2.22 on 2023-11-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
