# Generated by Django 3.2.22 on 2023-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20231108_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(blank=True, choices=[(3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5.0'), (5.5, '5.5'), (6.0, '6.0'), (6.5, '6.5'), (7.0, '7.0'), (7.5, '7.5'), (8.0, '8.0'), (8.5, '8.5'), (9.0, '9.0'), (9.5, '9.5'), (10.0, '10.0'), (10.5, '10.5'), (11.0, '11.0'), (11.5, '11.5'), (12.0, '12.0')], max_length=3, null=True),
        ),
    ]
