# Generated by Django 3.2.22 on 2024-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240123_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoesize',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.BooleanField(blank=True, max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='ShoeSize',
        ),
    ]
