# Generated by Django 3.2.22 on 2023-11-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
