# Generated by Django 3.2.22 on 2024-01-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240123_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
