# Generated by Django 3.2.22 on 2023-11-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20231108_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.BooleanField(blank=True, max_length=3, null=True),
        ),
    ]
