# Generated by Django 3.2.22 on 2024-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_shoe_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product', constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ('has_sizes', True), ('is_shoe', False)), models.Q(
                        ('has_sizes', False), ('is_shoe', True)), models.Q(
                            ('has_sizes', False), ('is_shoe', False)), _connector='OR'), name='one_of_has_sizes_or_is_shoe'), ), migrations.AddConstraint(
                                model_name='product', constraint=models.UniqueConstraint(
                                    condition=models.Q(
                                        ('has_sizes', True), ('is_shoe', True)), fields=(
                                            'has_sizes', 'is_shoe'), name='unique_has_sizes_and_is_shoe'), ), ]
