# Generated by Django 3.2.22 on 2024-02-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240206_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
