# Generated by Django 3.2.22 on 2024-02-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
